AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trabalhofinal

  Sample SAM Template for trabalhofinal

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  SaveCustomerService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SaveCustomerService
      Handler: savecustomer.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        SaveCustomer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: post
      Policies:
        - Statement:
            - Sid: DynamoDBWritePolicy
              Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/customer"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SaveCustomerApi:
    Description: "API Gateway endpoint URL for Prod stage for Save Customer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/savecustomer/"
  SaveCustomerFunction:
    Description: "Save Customer Lambda Function ARN"
    Value: !GetAtt SaveCustomerService.Arn
  SaveCustomerFunctionIamRole:
    Description: "Implicit IAM Role created for Save Customer function"
    Value: !GetAtt SaveCustomerServiceRole.Arn
