package data

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.util.*

@DynamoDBTable(tableName = "order")
data class Order(
        @DynamoDBAutoGeneratedKey
        @DynamoDBHashKey(attributeName = "orderId")
        var orderId: String = "",
        @DynamoDBAttribute(attributeName = "customer")
        var customerId: String? = null,
        @DynamoDBAttribute(attributeName = "salesman")
        var salesmanId: String? = null,
        @DynamoDBAttribute(attributeName = "items")
        var items: List<String>? = null,
        @DynamoDBAttribute(attributeName = "value")
        var value: Float? = null,
        @DynamoDBAttribute(attributeName = "deliveryDate")
        var deliveryDate: String? = null,
        @DynamoDBAttribute(attributeName = "purchaseDate")
        var purchaseDate: String? = null
)